# Generated by Django 6.0.3 on 2026-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
