# Generated by Django 6.0.3 on 2026-04-18 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_imagetoolhistory_resumeanalysishistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortened_urls_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VoiceToolHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('tts', 'Text to Speech'), ('stt', 'Speech to Text')], max_length=10)),
                ('input_data', models.TextField()),
                ('voice_used', models.CharField(blank=True, max_length=50, null=True)),
                ('output_result', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
