# Generated by Django 6.0.3 on 2026-04-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_urlshortener_user_voicetoolhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLShortener',
        ),
    ]
